# Generated by Django 3.2.15 on 2022-10-12 17:06

import apps.proyects.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import froala_editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_alter_category_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.ImageField(upload_to=apps.proyects.models.blog_directory_path)),
                ('dataset', models.FileField(upload_to=apps.proyects.models.blog_directory_path)),
                ('dataset_info', froala_editor.fields.FroalaField()),
                ('content', froala_editor.fields.FroalaField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
