# Generated by Django 3.2.15 on 2022-10-16 21:03

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='problem',
            field=froala_editor.fields.FroalaField(default=1),
            preserve_default=False,
        ),
    ]
