# Generated by Django 3.2.15 on 2022-10-16 23:08

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0002_projects_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='solution',
            field=froala_editor.fields.FroalaField(default=1),
            preserve_default=False,
        ),
    ]
