# Generated by Django 3.2.15 on 2022-10-20 19:00

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0003_projects_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='modelado',
            field=froala_editor.fields.FroalaField(default=1),
            preserve_default=False,
        ),
    ]
