# Generated by Django 3.2.15 on 2022-10-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0004_projects_modelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='repository',
            field=models.URLField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
