# Generated by Django 3.2.15 on 2022-09-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_verfied_useraccount_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='comprado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='salario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
